spring.application.name=BEACON

# Configuración por defecto con base de datos rápida en memoria
spring.datasource.url=jdbc:h2:mem:beacondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Ver consultas SQL en consola
spring.jpa.show-sql=false

# Puerto del servidor
server.port=8080
